//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dim_Turma
    {
        public Dim_Turma()
        {
            this.Dim_Aluno_Preceptor = new HashSet<Dim_Aluno_Preceptor>();
            this.Dim_Aula = new HashSet<Dim_Aula>();
        }
    
        public string id_turma { get; set; }
        public string nome_turma { get; set; }
        public string id_curso { get; set; }
        public string id_modulo { get; set; }
        public string id_hospital { get; set; }
        public Nullable<System.DateTime> data_insercao { get; set; }
        public Nullable<System.DateTime> data_atualizacao { get; set; }
    
        public virtual ICollection<Dim_Aluno_Preceptor> Dim_Aluno_Preceptor { get; set; }
        public virtual ICollection<Dim_Aula> Dim_Aula { get; set; }
        public virtual Dim_Curso Dim_Curso { get; set; }
        public virtual Dim_Hospital Dim_Hospital { get; set; }
        public virtual Dim_Modulo Dim_Modulo { get; set; }
    }
}
