//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dim_Professor
    {
        public Dim_Professor()
        {
            this.Dim_Aula = new HashSet<Dim_Aula>();
            this.Fato_Avaliacao = new HashSet<Fato_Avaliacao>();
        }
    
        public string id_professor { get; set; }
        public string id_especialidade { get; set; }
        public string nome_professor { get; set; }
        public string genero_professor { get; set; }
        public Nullable<System.DateTime> datanascimento_professor { get; set; }
        public string cpf_professor { get; set; }
        public Nullable<System.DateTime> data_insercao { get; set; }
        public Nullable<System.DateTime> data_atualizacao { get; set; }
    
        public virtual ICollection<Dim_Aula> Dim_Aula { get; set; }
        public virtual Dim_Especialidade Dim_Especialidade { get; set; }
        public virtual ICollection<Fato_Avaliacao> Fato_Avaliacao { get; set; }
    }
}
