//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dim_Aluno_Preceptor
    {
        public Dim_Aluno_Preceptor()
        {
            this.Fato_Permanencia_Plataforma = new HashSet<Fato_Permanencia_Plataforma>();
            this.Fato_Avaliacao = new HashSet<Fato_Avaliacao>();
            this.Fato_Plantao = new HashSet<Fato_Plantao>();
            this.Fato_Presenca = new HashSet<Fato_Presenca>();
        }
    
        public string id_aluno_preceptor { get; set; }
        public string idmatricula_aluno { get; set; }
        public string id_turma { get; set; }
        public string id_especialidade { get; set; }
        public string nome_aluno_preceptor { get; set; }
        public string tipo_aluno { get; set; }
        public Nullable<System.DateTime> datamatricula_aluno { get; set; }
        public string genero_aluno { get; set; }
        public Nullable<System.DateTime> datanasc_aluno { get; set; }
        public string cpf_aluno { get; set; }
        public Nullable<int> aluno_situacao { get; set; }
        public Nullable<System.DateTime> data_inativacao { get; set; }
        public Nullable<System.DateTime> data_insercao { get; set; }
        public Nullable<System.DateTime> data_atualizacao { get; set; }
    
        public virtual ICollection<Fato_Permanencia_Plataforma> Fato_Permanencia_Plataforma { get; set; }
        public virtual Dim_Especialidade Dim_Especialidade { get; set; }
        public virtual Dim_Turma Dim_Turma { get; set; }
        public virtual ICollection<Fato_Avaliacao> Fato_Avaliacao { get; set; }
        public virtual ICollection<Fato_Plantao> Fato_Plantao { get; set; }
        public virtual ICollection<Fato_Presenca> Fato_Presenca { get; set; }
    }
}
