//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dim_Aula
    {
        public Dim_Aula()
        {
            this.Fato_Presenca = new HashSet<Fato_Presenca>();
        }
    
        public string id_aula { get; set; }
        public string id_turma { get; set; }
        public string id_professor { get; set; }
        public string titulo_aula { get; set; }
        public Nullable<int> atividades_aula { get; set; }
        public Nullable<System.DateTime> data_aula { get; set; }
        public string tipo_aula { get; set; }
        public Nullable<System.DateTime> data_insercao { get; set; }
        public Nullable<System.DateTime> data_atualizacao { get; set; }
        public Nullable<System.DateTime> data_fim_aula { get; set; }
    
        public virtual Dim_Professor Dim_Professor { get; set; }
        public virtual Dim_Turma Dim_Turma { get; set; }
        public virtual ICollection<Fato_Presenca> Fato_Presenca { get; set; }
    }
}
