//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dim_Modulo
    {
        public Dim_Modulo()
        {
            this.Dim_Turma = new HashSet<Dim_Turma>();
            this.Fato_Avaliacao = new HashSet<Fato_Avaliacao>();
        }
    
        public string id_modulo { get; set; }
        public string nome_modulo { get; set; }
        public Nullable<System.DateTime> datainicio_modulo { get; set; }
        public Nullable<System.DateTime> datafim_modulo { get; set; }
        public Nullable<System.DateTime> data_insercao { get; set; }
        public Nullable<System.DateTime> data_atualizacao { get; set; }
    
        public virtual ICollection<Dim_Turma> Dim_Turma { get; set; }
        public virtual ICollection<Fato_Avaliacao> Fato_Avaliacao { get; set; }
    }
}
