//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fato_Avaliacao
    {
        public string id_avaliacao { get; set; }
        public string id_aluno_preceptor { get; set; }
        public string idmatricula_aluno { get; set; }
        public string id_turma { get; set; }
        public string id_professor { get; set; }
        public string id_modulo { get; set; }
        public Nullable<decimal> nota1_avaliacao { get; set; }
        public Nullable<decimal> nota2_avaliacao { get; set; }
        public Nullable<decimal> notaaf2_avaliacao { get; set; }
        public Nullable<decimal> nota3_avaliacao { get; set; }
        public Nullable<decimal> nota4_recuperacao { get; set; }
        public Nullable<decimal> notafinal_avaliacao { get; set; }
        public string resultado { get; set; }
        public Nullable<System.DateTime> data_insercao { get; set; }
        public Nullable<System.DateTime> data_atualizacao { get; set; }
    
        public virtual Dim_Aluno_Preceptor Dim_Aluno_Preceptor { get; set; }
        public virtual Dim_Modulo Dim_Modulo { get; set; }
        public virtual Dim_Professor Dim_Professor { get; set; }
    }
}
