//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fato_Permanencia_Plataforma
    {
        public System.DateTime data_entrada { get; set; }
        public string id_aluno_preceptor { get; set; }
        public string idmatricula_aluno { get; set; }
        public string id_turma { get; set; }
        public Nullable<System.DateTime> data_saida { get; set; }
        public Nullable<int> tempo_permanencia { get; set; }
        public string tipo_aluno { get; set; }
        public System.DateTime data_insercao { get; set; }
        public Nullable<System.DateTime> data_atualizacao { get; set; }
    
        public virtual Dim_Aluno_Preceptor Dim_Aluno_Preceptor { get; set; }
    }
}
