//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dim_Aluno_Preceptor> Dim_Aluno_Preceptor { get; set; }
        public virtual DbSet<Dim_Aula> Dim_Aula { get; set; }
        public virtual DbSet<Dim_Curso> Dim_Curso { get; set; }
        public virtual DbSet<Dim_Especialidade> Dim_Especialidade { get; set; }
        public virtual DbSet<Dim_Hospital> Dim_Hospital { get; set; }
        public virtual DbSet<Dim_Modulo> Dim_Modulo { get; set; }
        public virtual DbSet<Dim_Professor> Dim_Professor { get; set; }
        public virtual DbSet<Dim_Turma> Dim_Turma { get; set; }
        public virtual DbSet<Fato_Avaliacao> Fato_Avaliacao { get; set; }
        public virtual DbSet<Fato_Permanencia_Plataforma> Fato_Permanencia_Plataforma { get; set; }
        public virtual DbSet<Fato_Plantao> Fato_Plantao { get; set; }
        public virtual DbSet<Fato_Presenca> Fato_Presenca { get; set; }
        public virtual DbSet<Fato_Vaga_Curso_Unidade> Fato_Vaga_Curso_Unidade { get; set; }
        public virtual DbSet<LogErroAplicacao> LogErroAplicacao { get; set; }
    }
}
